export const AUDIT_ACTION_LABELS: Record<string, string> = {
  USER_REGISTERED: 'Utilizator înregistrat',
  LOGIN_SUCCESS: 'Autentificare reușită',
  LOGIN_FAILED: 'Autentificare eșuată',
  COMPANY_CREATED: 'Companie creată',
  COMPANY_PUBLISHED: 'Companie publicată',
  COMPANY_VERIFIED: 'Companie verificată',
  COMPANY_REJECTED: 'Companie respinsă',
  COMPANY_UNPUBLISHED: 'Publicare retrasă',
  COMPANY_SWITCHED: 'Companie activă schimbată',
  TEAM_MEMBER_ROLE_CHANGED: 'Rol membru schimbat',
  TEAM_MEMBER_DEACTIVATED: 'Membru dezactivat',
  TEAM_MEMBER_LEFT: 'Membru a părăsit echipa',
  TEAM_INVITATION_REVOKED: 'Invitație revocată',
  COMPANY_OWNERSHIP_TRANSFERRED: 'Proprietate transferată',
  SUBSCRIPTION_CHANGED: 'Plan abonament schimbat',
  REVIEW_MODERATED: 'Recenzie moderată',
  CONSENT_GRANTED: 'Consimțământ acordat',
  CONSENT_REVOKED: 'Consimțământ retras',
  ESTIMATE_SENT: 'Smetă trimisă clientului',
  ESTIMATE_ACCEPTED: 'Smetă acceptată de client',
  ESTIMATE_REJECTED: 'Smetă respinsă de client',
  ESTIMATE_CONVERTED: 'Smetă convertită în lucrări',
};

export const AUDIT_ACTION_FILTER_OPTIONS = [
  { value: 'COMPANY_VERIFIED', label: 'Verificare companie' },
  { value: 'COMPANY_REJECTED', label: 'Respingere companie' },
  { value: 'COMPANY_UNPUBLISHED', label: 'Retragere publicare' },
  { value: 'COMPANY_SWITCHED', label: 'Schimbare companie activă' },
  { value: 'TEAM_MEMBER_ROLE_CHANGED', label: 'Schimbare rol echipă' },
  { value: 'TEAM_MEMBER_DEACTIVATED', label: 'Dezactivare membru' },
  { value: 'TEAM_MEMBER_LEFT', label: 'Părăsire echipă' },
  { value: 'TEAM_INVITATION_REVOKED', label: 'Revocare invitație' },
  { value: 'COMPANY_OWNERSHIP_TRANSFERRED', label: 'Transfer proprietate' },
  { value: 'SUBSCRIPTION_CHANGED', label: 'Schimbare plan' },
  { value: 'REVIEW_MODERATED', label: 'Moderare recenzie' },
] as const;
