/**
 * Slug-и категорий со сметами (13 активных blueprint-ов).
 * Спецификация полей/modules по каждой категории — implementation_plan.md §4.1–4.13.
 */
export const ESTIMATE_BLUEPRINT_CATEGORY_SLUGS = [
  'santehnika',
  'elektrika',
  'clima',
  'lucrari-finisaj',
  'acoperis',
  'acoperis-plat',
  'fatade',
  'okna-dveri',
  'mobila',
  'cleaning',
  'it-networks',
  'it-hardware',
  'panouri-solare',
  'constructii',
  'pavaj',
] as const;

export type EstimateBlueprintCategorySlug = (typeof ESTIMATE_BLUEPRINT_CATEGORY_SLUGS)[number];

/**
 * Категории без смет — wizard показывает альтернативный сценарий (заявка, прайс и т.д.).
 * implementation_plan.md §3.
 */
export const ESTIMATE_EXCLUDED_CATEGORY_SLUGS = [
  'smm-marketing',
  'design-grafic',
  'frumusete-ingrijire',
  'asigurari',
  'servicii-juridice',
  'avto',
] as const;

export type EstimateExcludedCategorySlug = (typeof ESTIMATE_EXCLUDED_CATEGORY_SLUGS)[number];

export function isEstimateBlueprintCategorySlug(slug: string): slug is EstimateBlueprintCategorySlug {
  return (ESTIMATE_BLUEPRINT_CATEGORY_SLUGS as readonly string[]).includes(slug);
}

export function isEstimateExcludedCategorySlug(slug: string): slug is EstimateExcludedCategorySlug {
  return (ESTIMATE_EXCLUDED_CATEGORY_SLUGS as readonly string[]).includes(slug);
}

/**
 * Справочник: какие customField keys и workModule keys ожидаются по категории
 * (источник: implementation_tasks.md C-01–C-13). Blueprint config с API — runtime source of truth.
 */
export const ESTIMATE_CATEGORY_BLUEPRINT_SPEC: Record<
  EstimateBlueprintCategorySlug,
  { customFieldKeys: readonly string[]; workModuleKeys: readonly string[] }
> = {
  santehnika: {
    customFieldKeys: [
      'replacePipes',
      'filterSystem',
      'riserReplacement',
      'bathroomCount',
      'kitchenPoints',
      'bathroomPoints',
      'waterHeater',
      'pipeMaterial',
      'drainReplacement',
      'wallChasingM',
    ],
    workModuleKeys: ['water_pipes', 'drain', 'sanitary_objects', 'boiler', 'wall_chasing', 'testing'],
  },
  elektrika: {
    customFieldKeys: [
      'newPanel',
      'distributionBoardType',
      'cableReplace',
      'roomCount',
      'isNewConstruction',
      'socketCount',
      'switchCount',
      'lightPointCount',
      'deviceTier',
      'dedicatedLinesCount',
      'cableSegmentMm2',
      'wallChasingM',
      'wallMaterial',
      'panelModules',
      'smartHomeRequired',
      'voltageStabilizer',
      'groundingRequired',
    ],
    workModuleKeys: ['project', 'chasing', 'cabling', 'panel', 'devices', 'low_voltage', 'smart_home', 'testing'],
  },
  clima: {
    customFieldKeys: [
      'acUnits',
      'routeLengthM',
      'outdoorUnitCount',
      'indoorUnitCount',
      'drainLengthM',
      'wallCoreDrillingCount',
      'heightWork',
      'requiresPump',
      'equipmentIncluded',
      'maintenancePackage',
    ],
    workModuleKeys: ['route', 'indoor_outdoor_units', 'drain', 'pump', 'height_work', 'maintenance'],
  },
  'lucrari-finisaj': {
    customFieldKeys: [
      'finishArea',
      'wallHeight',
      'demolitionArea',
      'plasterArea',
      'puttyArea',
      'paintArea',
      'ceilingArea',
      'tileArea',
      'flooringArea',
      'screedArea',
      'drywallArea',
      'baseboardLengthM',
      'doorSlopeLengthM',
      'surfaceCondition',
      'finishLevel',
      'materialIncluded',
    ],
    workModuleKeys: [
      'demolition',
      'surface_preparation',
      'plaster',
      'putty',
      'paint',
      'wallpaper',
      'drywall',
      'ceiling',
      'tile',
      'flooring',
      'screed',
      'baseboards',
      'slopes',
      'cleaning',
    ],
  },
  'acoperis-plat': {
    customFieldKeys: [
      'roofArea',
      'waterproofingType',
      'insulationThicknessCm',
      'drainCount',
      'parapetLengthM',
      'parapetHeightM',
      'oldRoofRemoval',
      'isTerrace',
      'terraceArea',
      'skylightCount',
      'ballastIncluded',
    ],
    workModuleKeys: [
      'demolition',
      'vapor_barrier',
      'insulation',
      'waterproofing',
      'drains',
      'parapets',
      'terrace_finish',
      'skylights_flat',
      'ballast',
    ],
  },
  acoperis: {
    customFieldKeys: [
      'baseArea',
      'roofSlope',
      'roofShape',
      'valleyLengthM',
      'ridgeLengthM',
      'gutterLengthM',
      'wallIntersectionLengthM',
      'chimneyCount',
      'oldRoofRemoval',
      'insulationRequired',
      'soffitLengthM',
      'skylightCount',
      'gableArea',
      'roofDripEdgeLengthM',
    ],
    workModuleKeys: [
      'demolition',
      'timber_structure',
      'membrane',
      'insulation',
      'covering',
      'valleys',
      'wall_flashing',
      'gutters',
      'snow_guards',
      'soffit',
      'skylights',
      'gable',
      'roof_drip_edge',
    ],
  },
  fatade: {
    customFieldKeys: [
      'facadeArea',
      'scaffoldingArea',
      'insulationThicknessCm',
      'windowSlopeLengthM',
      'decorativePlasterArea',
      'basePlinthArea',
      'buildingHeightM',
      'oldPlasterArea',
      'repairArea',
      'exteriorSillLengthM',
      'facadeDripEdgeLengthM',
      'wallMaterial',
    ],
    workModuleKeys: [
      'scaffolding',
      'facade_demolition',
      'repairs',
      'preparation',
      'insulation',
      'mesh',
      'slopes',
      'decorative_plaster',
      'painting',
      'plinth',
      'window_sills',
      'facade_drip_edge',
    ],
  },
  'okna-dveri': {
    customFieldKeys: [
      'windowCount',
      'doorCount',
      'windowAreaM2',
      'doorAreaM2',
      'oldFrameRemoval',
      'sillCount',
      'mosquitoNetCount',
      'installationType',
      'profileClass',
      'glassPackage',
    ],
    workModuleKeys: [
      'measurement',
      'removal',
      'windows',
      'doors',
      'warm_installation',
      'sills',
      'slopes',
      'nets',
      'disposal',
    ],
  },
  mobila: {
    customFieldKeys: [
      'cabinetCount',
      'wardrobeCount',
      'linearMeters',
      'materialType',
      'hardwareTier',
      'drawerCount',
      'hingeCount',
      'countertopLengthM',
      'deliveryRequired',
      'installationRequired',
    ],
    workModuleKeys: ['design', 'cutting', 'hardware', 'assembly', 'countertop', 'delivery', 'installation'],
  },
  cleaning: {
    customFieldKeys: [
      'cleanArea',
      'cleaningType',
      'windowCount',
      'bathroomCount',
      'furniturePresent',
      'kitchenDeepClean',
      'trashRemoval',
      'afterRepairDustLevel',
    ],
    workModuleKeys: [
      'standard_cleaning',
      'deep_cleaning',
      'windows',
      'kitchen',
      'bathrooms',
      'post_construction',
      'trash_removal',
    ],
  },
  'it-networks': {
    customFieldKeys: [
      'itDirection',
      'projectScope',
      'pagesCount',
      'designPagesCount',
      'frontendPagesCount',
      'backendComplexity',
      'hasCMS',
      'hasEcommerce',
      'cameraCount',
      'networkPoints',
      'avgCableLengthPerPort',
      'apCount',
      'serverCount',
      'workstationCount',
      'rackUnits',
      'slaRequired',
      'documentationRequired',
      'migrationRequired',
    ],
    workModuleKeys: [
      'audit',
      'web_design',
      'frontend',
      'backend',
      'cms',
      'ecommerce',
      'network_cabling',
      'cameras',
      'servers',
      'security',
      'hardware_components',
      'migration',
      'sla',
    ],
  },
  'it-hardware': {
    customFieldKeys: [
      'deviceCount',
      'deviceType',
      'repairCount',
      'repairComplexity',
      'assemblyCount',
      'upgradeCount',
      'cleaningHwCount',
      'osInstallCount',
      'osType',
      'dataRecoveryCount',
      'recoverySeverity',
      'peripheralCount',
      'peripheralType',
      'warrantyMonths',
    ],
    workModuleKeys: [
      'diagnostic_hw',
      'repair',
      'assembly',
      'upgrade',
      'cleaning_hw',
      'os_install',
      'data_recovery',
      'peripheral',
    ],
  },
  'panouri-solare': {
    customFieldKeys: [
      'panelCount',
      'batteryCapacity',
      'inverterCount',
      'systemPowerKw',
      'roofType',
      'gridConnection',
      'cableLengthM',
      'structureType',
      'permitsRequired',
      'monitoringRequired',
    ],
    workModuleKeys: [
      'audit',
      'project',
      'mounts',
      'panels',
      'inverter',
      'batteries',
      'protection',
      'grid_connection',
      'permits',
      'monitoring',
    ],
  },
  constructii: {
    customFieldKeys: [
      'builtArea',
      'storyCount',
      'foundationType',
      'wallMaterial',
      'slabType',
      'excavationVolumeM3',
      'concreteVolumeM3',
      'rebarKg',
      'masonryVolumeM3',
      'roofIncluded',
      'utilitiesIncluded',
      'projectDocumentation',
    ],
    workModuleKeys: [
      'constructii_project',
      'excavation',
      'foundation',
      'waterproofing',
      'structure',
      'slab',
      'stairs',
      'roof',
      'utilities',
    ],
  },
  pavaj: {
    customFieldKeys: [
      'pavementArea',
      'borderLengthM',
      'baseLayerCm',
      'paverThicknessCm',
      'drainageRequired',
      'oldSurfaceRemovalArea',
      'geotextileRequired',
      'sandLayerCm',
      'gravelLayerCm',
      'patternComplexity',
      'vehicleLoad',
    ],
    workModuleKeys: [
      'removal',
      'excavation',
      'geotextile',
      'gravel',
      'sand',
      'borders',
      'drainage',
      'paving',
      'compaction',
    ],
  },
};
