import { COMPANY_CABINET_PATH } from '@/shared/constants/routes.constants';
import { COMPANY_ROLE_GROUPS } from '@/entities/company/model/roles.constants';
import type { CompanyRole } from '@/entities/company/model/roles.types';

export const COMPANY_ROUTE_ROLES: Record<string, readonly CompanyRole[]> = {
  [COMPANY_CABINET_PATH.DASHBOARD]: COMPANY_ROLE_GROUPS.ALL_STAFF,
  [COMPANY_CABINET_PATH.PROFILE]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.GALLERY]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.CLIENTI]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.PIPELINE]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.LUCRARI]: COMPANY_ROLE_GROUPS.ALL_STAFF,
  [COMPANY_CABINET_PATH.LUCRARI_MY]: COMPANY_ROLE_GROUPS.MEMBER_ONLY,
  [COMPANY_CABINET_PATH.CALENDAR]: COMPANY_ROLE_GROUPS.ALL_STAFF,
  [COMPANY_CABINET_PATH.SERVICII]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.CERERI]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.OFERTE]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.SMETE]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.SMETE_TEMPLATES]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.FACTURI]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.RECENZII]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.TEAM]: COMPANY_ROLE_GROUPS.MANAGEMENT,
  [COMPANY_CABINET_PATH.SUBSCRIPTION]: COMPANY_ROLE_GROUPS.OWNER_ONLY,
  [COMPANY_CABINET_PATH.AUDIT]: COMPANY_ROLE_GROUPS.OWNER_ONLY,
};
