export const DEFAULT_REQUEST_TIMEOUT_MS = 30_000;
export const DOWNLOAD_REQUEST_TIMEOUT_MS = Math.max(DEFAULT_REQUEST_TIMEOUT_MS, 120_000);
export const STREAM_DOWNLOAD_THRESHOLD_BYTES = 5 * 1024 * 1024;
