import type { EstimateBlueprintCategorySlug } from './estimateCategorySlugs.constants';

type CategorySpec = { customFieldKeys: readonly string[]; workModuleKeys: readonly string[] };

export const blueprintItSpec = {
  'it-networks': {
    customFieldKeys: [
      'cameraCount',
      'networkPoints',
      'avgCableLengthPerPort',
      'apCount',
      'serversToConfigure',
      'serversToAssemble',
      'workstationsToConfigure',
      'workstationsToAssemble',
      'rackUnits',
      'siteSurveyRequired',
      'commissioningRequired',
      'slaRequired',
      'documentationRequired',
      'migrationRequired',
    ],
    workModuleKeys: [
      'site_survey',
      'network_cabling',
      'cameras',
      'servers',
      'security',
      'hardware_components',
      'commissioning',
      'migration',
      'sla',
    ],
  },
  'it-hardware': {
    customFieldKeys: [
      'deviceCount',
      'deviceType',
      'simpleRepairCount',
      'mediumRepairCount',
      'complexRepairCount',
      'assemblyCount',
      'upgradeCount',
      'cleaningHwCount',
      'osInstallCount',
      'osType',
      'logicRecoveryCount',
      'physicalRecoveryCount',
      'severeRecoveryCount',
      'peripheralCount',
      'peripheralType',
      'warrantyMonths',
    ],
    workModuleKeys: [
      'diagnostic_hw',
      'repair',
      'assembly',
      'upgrade',
      'cleaning_hw',
      'os_install',
      'data_recovery',
      'peripheral',
    ],
  },
  'it-web': {
    customFieldKeys: [
      'projectScope',
      'pagesCount',
      'designPagesCount',
      'frontendPagesCount',
      'backendComplexity',
      'hasCMS',
      'hasEcommerce',
      'documentationRequired',
      'migrationRequired',
      'slaRequired',
    ],
    workModuleKeys: [
      'audit',
      'web_design',
      'frontend',
      'backend',
      'cms',
      'ecommerce',
      'security',
      'migration',
      'sla',
    ],
  },
} satisfies Partial<Record<EstimateBlueprintCategorySlug, CategorySpec>>;