import type { EstimateBlueprintCategorySlug } from './estimateCategorySlugs.constants';

type CategorySpec = { customFieldKeys: readonly string[]; workModuleKeys: readonly string[] };

export const blueprintFinishingSpec = {
  'lucrari-finisaj': {
    customFieldKeys: [
      'finishArea',
      'wallHeight',
      'surfaceCondition',
      'finishLevel',
      'materialIncluded',
      'demolitionArea',
      'plasterArea',
      'partitionArea',
      'ceilingArea',
      'drywallArea',
      'stretchCeilingArea',
      'decorativePlasterArea',
      'wallpaperArea',
      'paintArea',
      'waterproofingArea',
      'tileArea',
      'screedArea',
      'flooringArea',
      'parquetArea',
      'baseboardLengthM',
      'doorSlopeLengthM',
    ],
    workModuleKeys: [
      'demolition',
      'surface_preparation',
      'plaster',
      'partition',
      'putty',
      'paint',
      'decorative_plaster',
      'wallpaper',
      'ceiling',
      'drywall',
      'stretch_ceiling',
      'waterproofing',
      'tile',
      'screed',
      'flooring',
      'parquet',
      'baseboards',
      'slopes',
      'cleaning',
    ],
  },
  acoperis: {
    customFieldKeys: [
      'baseArea',
      'roofSlope',
      'roofShape',
      'valleyLengthM',
      'ridgeLengthM',
      'gutterLengthM',
      'wallIntersectionLengthM',
      'chimneyCount',
      'oldRoofRemoval',
      'insulationRequired',
      'soffitLengthM',
      'skylightCount',
      'gableArea',
      'roofDripEdgeLengthM',
    ],
    workModuleKeys: [
      'demolition',
      'timber_structure',
      'membrane',
      'insulation',
      'covering',
      'valleys',
      'wall_flashing',
      'gutters',
      'snow_guards',
      'soffit',
      'skylights',
      'gable',
      'roof_drip_edge',
    ],
  },
  'acoperis-plat': {
    customFieldKeys: [
      'roofArea',
      'waterproofingType',
      'insulationThicknessCm',
      'drainCount',
      'parapetLengthM',
      'parapetHeightM',
      'oldRoofRemoval',
      'isTerrace',
      'terraceArea',
      'skylightCount',
      'ballastIncluded',
    ],
    workModuleKeys: [
      'demolition',
      'vapor_barrier',
      'insulation',
      'waterproofing',
      'drains',
      'parapets',
      'terrace_finish',
      'skylights_flat',
      'ballast',
    ],
  },
  fatade: {
    customFieldKeys: [
      'facadeArea',
      'scaffoldingArea',
      'insulationThicknessCm',
      'windowSlopeLengthM',
      'decorativePlasterArea',
      'basePlinthArea',
      'buildingHeightM',
      'oldPlasterArea',
      'repairArea',
      'exteriorSillLengthM',
      'facadeDripEdgeLengthM',
      'wallMaterial',
    ],
    workModuleKeys: [
      'scaffolding',
      'facade_demolition',
      'repairs',
      'preparation',
      'insulation',
      'mesh',
      'slopes',
      'decorative_plaster',
      'painting',
      'plinth',
      'window_sills',
      'facade_drip_edge',
    ],
  },
  'okna-dveri': {
    customFieldKeys: [
      'windowCount',
      'doorCount',
      'installationType',
      'oldFrameRemoval',
      'sillCount',
      'mosquitoNetCount',
    ],
    workModuleKeys: [
      'measurement',
      'removal',
      'windows',
      'doors',
      'warm_installation',
      'sills',
      'slopes',
      'nets',
      'disposal',
    ],
  },
} satisfies Partial<Record<EstimateBlueprintCategorySlug, CategorySpec>>;