import type { EstimateBlueprintCategorySlug } from './estimateCategorySlugs.constants';

type CategorySpec = { customFieldKeys: readonly string[]; workModuleKeys: readonly string[] };

export const blueprintConstructionSpec = {
  santehnika: {
    customFieldKeys: [
      'replacePipes',
      'filterSystem',
      'riserReplacement',
      'bathroomCount',
      'kitchenPoints',
      'bathroomPoints',
      'waterHeater',
      'pipeMaterial',
      'drainReplacement',
      'wallChasingM',
    ],
    workModuleKeys: ['water_pipes', 'drain', 'sanitary_objects', 'boiler', 'wall_chasing', 'testing'],
  },
  elektrika: {
    customFieldKeys: [
      'newPanel',
      'distributionBoardType',
      'cableReplace',
      'roomCount',
      'isNewConstruction',
      'socketCount',
      'switchCount',
      'lightPointCount',
      'deviceTier',
      'dedicatedLinesCount',
      'cableSegmentMm2',
      'wallChasingM',
      'wallMaterial',
      'panelModules',
      'smartHomeRequired',
      'voltageStabilizer',
      'groundingRequired',
    ],
    workModuleKeys: ['project', 'chasing', 'cabling', 'panel', 'devices', 'low_voltage', 'smart_home', 'testing'],
  },
  clima: {
    customFieldKeys: [
      'acUnits',
      'routeLengthM',
      'outdoorUnitCount',
      'indoorUnitCount',
      'drainLengthM',
      'wallCoreDrillingCount',
      'heightWork',
      'requiresPump',
      'equipmentIncluded',
      'maintenancePackage',
    ],
    workModuleKeys: ['route', 'indoor_outdoor_units', 'drain', 'pump', 'height_work', 'maintenance'],
  },
  constructii: {
    customFieldKeys: [
      'builtArea',
      'storyCount',
      'foundationType',
      'wallMaterial',
      'slabType',
      'excavationVolumeM3',
      'concreteVolumeM3',
      'rebarKg',
      'masonryVolumeM3',
      'roofIncluded',
      'utilitiesIncluded',
      'projectDocumentation',
    ],
    workModuleKeys: [
      'constructii_project',
      'excavation',
      'foundation',
      'waterproofing',
      'structure',
      'slab',
      'stairs',
      'roof',
      'utilities',
    ],
  },
  pavaj: {
    customFieldKeys: [
      'pavementArea',
      'borderLengthM',
      'vehicleLoad',
      'drainageRequired',
      'patternComplexity',
      'baseLayerCm',
      'gravelLayerCm',
      'sandLayerCm',
      'geotextileRequired',
      'concreteBaseArea',
      'stepsLengthM',
      'manholeCount',
      'oldSurfaceRemovalArea',
    ],
    workModuleKeys: [
      'removal',
      'excavation',
      'geotextile',
      'gravel',
      'sand',
      'concrete_base',
      'borders',
      'paving',
      'steps',
      'drainage',
      'manholes',
      'compaction',
    ],
  },
} satisfies Partial<Record<EstimateBlueprintCategorySlug, CategorySpec>>;